version: 0.2
phases:
  install: # Install AWS cli, kubectl and Helm3
    commands:
       - apt-get update
       - apt-get install -y git python3 python3-pip gnupg unzip
       - pip install awscli
       - pip install git-remote-codecommit
       - curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
       - chmod +x ./aws-iam-authenticator
       - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin

       - curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip 
       # - curl -LO https://keybase.io/hashicorp/pgp_keys.asc 
       # - gpg --import pgp_keys.asc
       # - gpg --fingerprint --list-signatures "HashiCorp Security" | grep -q "C874 011F 0AB4 0511 0D02  1055 3436 5D94 72D7 468F" || exit 1
       # - gpg --fingerprint --list-signatures "HashiCorp Security" | grep -q "34365D9472D7468F" || exit 1
       # - curl -sSL https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS 
       # - curl -sSL https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig 
       # - gpg --verify terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig terraform_${TERRAFORM_VERSION}_SHA256SUMS || exit 1
       # - sha256sum -c terraform_${TERRAFORM_VERSION}_SHA256SUMS 2&gt;&amp;1 | grep -q "terraform_${TERRAFORM_VERSION}_linux_amd64.zip: OK" || exit 1
       - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin
       - chmod +x /usr/local/bin/terraform 
  pre_build: # Check helm version and Add kubeconfig to access to EKS cluster and check readiness of the cluster
    commands:
      - terraform init -input=false
      - "aws ecs describe-clusters --clusters=$ECS_CLUSTER_NAME"
      - "chmod 0600 ~/.kube/config"
      - "aws sts get-caller-identity"
  
  build: # Deploy app via Helm
    commands:
      - sed -i "s|container_image=\".*\"|container_image=\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION\"|" ./terraform.tfvars  
      - terraform apply -input=false -compact-warnings -auto-approve
  
  post_build: 
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
